version: '3.8'

services:
  asistente:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
    env_file: 
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia  # IMPORTANTE para usar GPU
